### DISCUSSION TITLE
RGB Node API for smart contract state

### DISCUSSION THREAD

**Discussion by dr-orlovsky** [RGB-WG/rgb-node#221] [Ideas]
It is planned to generalize RGB Node API for reading the state of RGB smart contracts, which will be (a) abstracted from a specific schema but (b) still be able to provide all information necessary for the wallets without the use of schema-specific parsing libraries (like `rust-rgb20` and `rust-rgb21`).

How response from the node may look like? I think about something in the form of:

```yaml
id: rgb1.....
schema: rgbsch1....
rgb20:
   name: Asset Name
   ticker: AST
   issue: 
      cap: ~ # total cap is not known
      known: 100_000
      unknown: false # there is no unknown issues, thus `known` is total issued assets
   allocations:
      - amount: 1000
        txid: 405674adda3e32e063f17a1e0aa3548123512c08f8a9512d2d996040c96a8b78
        vout: 1
```

Of course these data can be provided in JSON, I am using YAML here just for the higher readability.

In order to get RGB Node doing this stuff we need to introduce "RGB interface" and transform things like RGB20, 21 etc into an abstract interfaces covering multiple schema (and schema able to implement multiple interfaces). This will also simplify independent schema development.

The way interface and its implementation for a schema may look like is shown in https://github.com/orgs/RGB-WG/discussions/218, section "API exposed by contracts". These APIs will be compiled into ABI files which can be imported into the Node and used for parsing contract state.

The schemata will be specifying which ABI they support, and these data will not be a part of the consensus, but a part of the "schema package" distributed by schema devs, which, additionally to the schema consensus data will contain meta-information about the schema, including ABI, and will be signed by the schema developer. Such packages may be distributed via curated centralized registry such as https://github.com/RGB-WG/schemata or Storm; the curated registry will be more preferable to prevent hacky schema distribution on the initial stages until users will be well-aware about which schema developers they should trust by using WoT-like identities.

Schema interface (ABI files) will map schema-specific type ids to a standard types defined by a schema interface standard (such as RGB20):

```yaml
standard: RGB20
owned_state_map:
   asset: 60
   inflation: 61
transition_map:
   transfer: 60
   inflation: ....
```
